hw4 - mock server
dyanov/gbshop pull request #4
Opened 2021-07-12 13:43 UTC by dyanov

2021-07-15 13:46 UTC, DrBoat requested changes
Так, давай переносить все на Heroku и потом вливать

2021-07-15 13:46 UTC, DrBoat commented on gbshop/App/BussinessLogic/Network/User/UserRequestFactory.swift
> -
Спорное решение не делить функции пустыми строками в протоколе, но как всегда оставляю кодстайл на твое усмотрение. Главное точу везде было одинакого!

2021-07-15 13:46 UTC, DrBoat commented on gbshop/Server/ServerPath.swift
> +enum ServerPath: String {
Хорошее решение, лайк

2021-07-15 13:46 UTC, DrBoat commented on gbshop/Server/ServerPath.swift
> +enum ServerPath: String {
Но нужно было все апи перенести на свой сервер и избавиться от `geekBrainsBaseUrl`

2021-07-15 13:46 UTC, DrBoat commented on gbshop/App/BussinessLogic/Network/User/UserRequestFactoryRealise.swift
> +    let baseUrl = URL(string: ServerPath.localBaseUrl.rawValue)!
herokuBaseUrl и везде дальше тоже. Я не смогу с таким протестировать)

2021-07-20 20:22 UTC, dyanov commented on gbshop/App/BussinessLogic/Network/User/UserRequestFactory.swift
> -
Согласен, надо бы поправить

2021-07-20 20:22 UTC, dyanov commented on gbshop/Server/ServerPath.swift
> +enum ServerPath: String {
Сдам в следующем PR

2021-07-20 20:41 UTC, merged